# Generated by Django 4.2.6 on 2023-10-18 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ManagedSystemCPU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hmc_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='HMC Name')),
                ('ms_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Managed System')),
                ('ms_model', models.CharField(blank=True, max_length=150, null=True, verbose_name='Managed System Type')),
                ('ms_power_type', models.CharField(blank=True, max_length=150, null=True, verbose_name='Managed System CPU Type')),
                ('configurable_sys_proc_units', models.CharField(blank=True, null=True, verbose_name='Configurable Proc Units')),
                ('curr_avail_sys_proc_units', models.CharField(blank=True, null=True, verbose_name='Available Proc Units')),
                ('deconfig_sys_proc_units', models.CharField(blank=True, max_length=150, null=True, verbose_name='Deconfigured Proc Units')),
            ],
            options={
                'verbose_name': 'MS CPU Config',
                'verbose_name_plural': 'Managed System CPU',
                'db_table': 'ms_cpu',
            },
        ),
        migrations.CreateModel(
            name='ManagedSystemMemory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hmc_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='HMC Name')),
                ('ms_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Managed System')),
                ('configurable_sys_mem', models.CharField(blank=True, null=True, verbose_name='Configurable Memory')),
                ('curr_avail_sys_mem', models.CharField(blank=True, null=True, verbose_name='Available Memory')),
                ('deconfig_sys_mem', models.CharField(blank=True, null=True, verbose_name='Deconfigured Memory')),
                ('sys_firmware_mem', models.CharField(blank=True, null=True, verbose_name='System Firmware Memory')),
                ('mem_region_size', models.CharField(blank=True, null=True, verbose_name='Memory Region Size')),
            ],
            options={
                'verbose_name_plural': 'Managed System Memory',
                'db_table': 'ms_mem',
            },
        ),
        migrations.CreateModel(
            name='ManagedSystemVM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hmc_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='HMC Name')),
                ('ms_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Managed System')),
                ('ms_model', models.CharField(blank=True, max_length=50, null=True, verbose_name='Managed System Model')),
                ('ms_power_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='Managed System Type')),
                ('ms_serial', models.CharField(blank=True, max_length=50, null=True, verbose_name='Managed System Serial')),
                ('lpar_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Lpar Name')),
                ('lpar_env', models.CharField(blank=True, max_length=50, null=True, verbose_name='Lpar Env')),
                ('lpar_os', models.CharField(blank=True, max_length=100, null=True, verbose_name='Lpar OS')),
                ('lpar_state', models.CharField(blank=True, max_length=50, null=True, verbose_name='Lpar State')),
                ('lpar_ip', models.CharField(blank=True, max_length=150, null=True, verbose_name='Lpar IP Address')),
                ('rmc_state', models.CharField(blank=True, max_length=20, null=True, verbose_name='RMC State')),
                ('curr_lpar_proc_compat_mode', models.CharField(blank=True, max_length=20, null=True, verbose_name='Proc Compat Mode')),
                ('lpar_id', models.CharField(blank=True, null=True, verbose_name='LPAR ID')),
            ],
            options={
                'verbose_name': 'LPARS',
                'verbose_name_plural': 'LPAR Inventory',
                'db_table': 'lpar_ms',
            },
        ),
        migrations.CreateModel(
            name='MemoryCpuVM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Profile Name')),
                ('lpar_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='LPAR Name')),
                ('min_mem', models.CharField(blank=True, null=True, verbose_name='Min Memory')),
                ('desired_mem', models.CharField(blank=True, null=True, verbose_name='Desired Memory')),
                ('max_mem', models.CharField(blank=True, null=True, verbose_name='Max Memory')),
                ('mem_mode', models.CharField(blank=True, null=True, verbose_name='Memory Mode')),
                ('proc_mode', models.CharField(blank=True, null=True, verbose_name='CPU Mode')),
                ('min_proc_units', models.CharField(blank=True, null=True, verbose_name='Min Proc Units')),
                ('desired_proc_units', models.CharField(blank=True, null=True, verbose_name='Desired Proc Units')),
                ('max_proc_units', models.CharField(blank=True, null=True, verbose_name='Max Proc Units')),
                ('min_procs', models.CharField(blank=True, null=True, verbose_name='Min Procs')),
                ('desired_procs', models.CharField(blank=True, null=True, verbose_name='Desired Procs')),
                ('max_procs', models.CharField(blank=True, null=True, verbose_name='Max Procs')),
                ('sharing_mode', models.CharField(blank=True, null=True, verbose_name='Sharing Mode')),
                ('uncap_weight', models.CharField(blank=True, default=128, null=True, verbose_name='Uncapped Weight')),
            ],
            options={
                'verbose_name': 'Memory/CPU Config',
                'verbose_name_plural': 'Memory / CPU for LPARs',
                'db_table': 'mem_cpu_lpars',
            },
        ),
    ]
