# Generated by Django 4.2.6 on 2023-10-18 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource_reports', '0002_alter_managedsystemcpu_configurable_sys_proc_units_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managedsystemmemory',
            name='mem_region_size',
            field=models.FloatField(blank=True, default=256, null=True, verbose_name='Memory Region Size'),
        ),
    ]
