# Generated by Django 4.2.6 on 2023-10-18 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource_reports', '0003_alter_managedsystemmemory_mem_region_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managedsystemmemory',
            name='sys_firmware_mem',
            field=models.FloatField(blank=True, null=True, verbose_name='System Firmware Memory'),
        ),
        migrations.AlterField(
            model_name='managedsystemvm',
            name='lpar_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='LPAR ID'),
        ),
        migrations.AlterField(
            model_name='memorycpuvm',
            name='sharing_mode',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Sharing Mode'),
        ),
    ]
